### ISSUE TITLE
Error when I get videos with disable comments

### ISSUE THREAD

**Issue by avivasa** [pdrm83/Youtube_API_Wrapper#1]
Hi, congratulations for your project.  When I search videos  with disable comments (ID : BW4fYZHVhfk)  on youtube I get this error:

~/.local/lib/python3.8/site-packages/youtube_easy_api/easy_wrapper.py in get_metadata(self, video_id)
     89         output['D'] = results['statistics']
     90 
---> 91         if results['statistics']['commentCount']:
     92             output['comments'] = self.extract_video_comments(self.service,
     93                                                              part='snippet',

KeyError: 'commentCount'

Thank you

**Comment by pdrm83** [comment]
Thanks for your feedback. It must be resolved now. Could you please verify?

**Comment by avivasa** [comment]
Hi, thank you for your message. I unistall and install the library and I had the same error.   What I need to do to update the package? I think that is the same version in the repository. 
Error
KeyError: 'commentCount'

Thank you

**Comment by pdrm83** [comment]
Sorry, I thought you forked the project. I updated the repository but I didn't update package. Will update the package tomorrow.

**Comment by avivasa** [comment]
Hi, thank you. I get the code and it works. Congratulations for your project.

**Comment by pdrm83** [comment]
I updated the PyPi package as well. If you think issue is resolved, please kindly close it. Plus, you are more than welcome to contribute to this project for further development. Thanks!

**Comment by avivasa** [comment]
Hi, I will update the package.  I really liked the project and would like to contribute.Thank you again.
